require('dotenv').config({ path: '../../.env' }); // 引入环境变量

const server_port = process.env.SERVER_PORT; // 定义POST

module.exports = [
    `http://localhost:${server_port}/avater_img/1.png`,
    `http://localhost:${server_port}/avater_img/2.png`,
    `http://localhost:${server_port}/avater_img/3.png`,
    `http://localhost:${server_port}/avater_img/4.png`,
    `http://localhost:${server_port}/avater_img/5.png`,
    `http://localhost:${server_port}/avater_img/6.png`,
    `http://localhost:${server_port}/avater_img/7.png`,
    `http://localhost:${server_port}/avater_img/8.png`,
    `http://localhost:${server_port}/avater_img/9.png`,
    `http://localhost:${server_port}/avater_img/10.png`,
    `http://localhost:${server_port}/avater_img/11.png`,
    `http://localhost:${server_port}/avater_img/12.png`,
    `http://localhost:${server_port}/avater_img/13.png`,
    `http://localhost:${server_port}/avater_img/14.png`,
    `http://localhost:${server_port}/avater_img/15.png`,
    `http://localhost:${server_port}/avater_img/16.png`,
    `http://localhost:${server_port}/avater_img/17.png`,
    `http://localhost:${server_port}/avater_img/18.png`,
    `http://localhost:${server_port}/avater_img/19.png`,
    `http://localhost:${server_port}/avater_img/20.png`,
    `http://localhost:${server_port}/avater_img/21.png`,
    `http://localhost:${server_port}/avater_img/22.png`,
    `http://localhost:${server_port}/avater_img/23.png`,
    `http://localhost:${server_port}/avater_img/24.png`,
    `http://localhost:${server_port}/avater_img/25.png`,
    `http://localhost:${server_port}/avater_img/26.png`,
    `http://localhost:${server_port}/avater_img/27.png`,
    `http://localhost:${server_port}/avater_img/28.png`,
    `http://localhost:${server_port}/avater_img/29.png`,
    `http://localhost:${server_port}/avater_img/30.png`,
    `http://localhost:${server_port}/avater_img/31.png`,
    `http://localhost:${server_port}/avater_img/32.png`,
    `http://localhost:${server_port}/avater_img/33.png`,
    `http://localhost:${server_port}/avater_img/34.png`,
    `http://localhost:${server_port}/avater_img/35.png`,
]